import type { AppState, JourneyPhase } from "./types";

export const phaseMeta: Record<JourneyPhase, { label: string; number: string; color: string }> = {
  admission: { label: "錄取與學校申請", number: "01", color: "blue" },
  visa: { label: "簽證與財力準備", number: "02", color: "yellow" },
  "pre-departure": { label: "住宿與行前手續", number: "03", color: "terracotta" },
  "arrival-72h": { label: "抵達 72 小時", number: "04", color: "sage" },
  "arrival-2w": { label: "抵達後兩週", number: "05", color: "blue" },
  semester: { label: "學期中生活與學業", number: "06", color: "yellow" },
  return: { label: "返國與註銷", number: "07", color: "terracotta" },
};

export const defaultState: AppState = {
  version: 1,
  dataRevision: 3,
  journey: {
    id: "my-exchange-journey",
    kind: "exchange",
    title: "我的交換旅程",
    ownerName: "交換生",
    homeCity: "Taipei",
    hostCity: "交換城市",
    hostSchool: "請在設定中填寫學校",
    program: "交換計畫",
    startDate: "2027-03-01",
    endDate: "2028-02-28",
    orientationDate: "2027-03-02",
    destinations: ["Germany"],
  },
  tasks: [
    {
      id: "accept-place",
      title: "確認並接受交換名額",
      description: "保存錄取通知，確認交換期間、學院與回覆期限。",
      phase: "admission",
      status: "not-started",
      priority: "high",
      dueDate: "2026-10-01",
      predecessorIds: [],
      notes: "請依自己的錄取信修改期限與內容。",
      templateKind: "school-admin",
      checklist: [
        { id: "offer-letter", label: "保存錄取通知", done: false },
        { id: "acceptance-reply", label: "回覆接受名額", done: false },
      ],
      records: [],
    },
    {
      id: "school-application",
      title: "完成交換學校申請",
      description: "依學校要求準備申請表、語言證明、成績單與交換期間資料。",
      phase: "admission",
      status: "not-started",
      priority: "high",
      predecessorIds: ["accept-place"],
      notes: "",
      templateKind: "school-admin",
      checklist: [
        { id: "school-portal", label: "完成交換學校系統資料", done: false },
        { id: "school-confirmation", label: "收到學校確認", done: false },
      ],
      records: [],
    },
    {
      id: "learning-agreement",
      title: "確認選課與 Learning Agreement",
      description: "核對當學期課程、ECTS、簽署人與母校學分認定方式。",
      phase: "admission",
      status: "not-started",
      priority: "high",
      predecessorIds: ["school-application"],
      notes: "",
      templateKind: "course",
      checklist: [
        { id: "course-list", label: "取得最新課程清單", done: false },
        { id: "la-signature", label: "完成雙方簽署", done: false },
      ],
      records: [],
    },
    {
      id: "financial-proof",
      title: "準備簽證財力證明",
      description: "依目的國最新規定確認限制帳戶、獎學金或其他可接受的財力證明。",
      phase: "visa",
      status: "not-started",
      priority: "high",
      predecessorIds: ["accept-place"],
      notes: "金額與格式會變動，送件前必須回官方來源重查。",
      templateKind: "payment",
      checklist: [
        { id: "funding-rule", label: "查核當年度財力規定", done: false },
        { id: "funding-confirmation", label: "保存正式財力證明", done: false },
      ],
      records: [],
    },
    {
      id: "visa-application",
      title: "完成學生簽證申請",
      description: "確認管轄單位、申請入口、文件清單、費用與面談安排。",
      phase: "visa",
      status: "not-started",
      priority: "high",
      predecessorIds: ["financial-proof", "school-application"],
      notes: "不要在手帳中貼入護照號碼、帳戶或完整文件內容。",
      templateKind: "visa",
      checklist: [
        { id: "visa-official-list", label: "依官方清單備妥文件", done: false },
        { id: "visa-submitted", label: "記錄正式送件日期", done: false },
        { id: "visa-appointment", label: "將面談加入行事曆", done: false },
      ],
      records: [],
    },
    {
      id: "housing",
      title: "確認住宿與入住方式",
      description: "追蹤住宿申請、合約、押金、入住日與鑰匙領取方式。",
      phase: "pre-departure",
      status: "not-started",
      priority: "high",
      predecessorIds: ["school-application"],
      notes: "本站只記錄狀態；合約、房號與付款資料請留在私人文件夾。",
      templateKind: "housing",
      checklist: [
        { id: "housing-confirmed", label: "收到住宿確認", done: false },
        { id: "move-in-plan", label: "確認鑰匙與入住流程", done: false },
      ],
      records: [],
    },
    {
      id: "insurance",
      title: "確認健康保險",
      description: "查核簽證、入學與在地生活各階段可接受的保險證明。",
      phase: "pre-departure",
      status: "not-started",
      priority: "high",
      predecessorIds: ["school-application"],
      notes: "",
      checklist: [
        { id: "insurance-coverage", label: "確認保障起訖與適用性", done: false },
        { id: "insurance-certificate", label: "保存保險證明副本", done: false },
      ],
      records: [],
    },
    {
      id: "flight",
      title: "安排去程班機與落地交通",
      description: "記錄起飛、轉機、抵達與第一晚交通，不在分享版放訂位代碼。",
      phase: "pre-departure",
      status: "not-started",
      priority: "medium",
      predecessorIds: ["visa-application", "housing"],
      notes: "",
      templateKind: "flight",
      checklist: [
        { id: "flight-booked", label: "確認班機時間與行李額度", done: false },
        { id: "arrival-route", label: "保存機場到住宿的備案", done: false },
      ],
      records: [],
    },
    {
      id: "document-pack",
      title: "整理隨身文件包與備份",
      description: "列出需要隨身攜帶、雲端備份與交由家人留存的文件。",
      phase: "pre-departure",
      status: "not-started",
      priority: "high",
      predecessorIds: ["visa-application", "insurance", "housing"],
      notes: "本網站不提供文件上傳。",
      checklist: [
        { id: "carry-documents", label: "完成隨身紙本文件包", done: false },
        { id: "cloud-copy", label: "建立私人雲端副本", done: false },
        { id: "family-copy", label: "留一份必要資料給家人", done: false },
      ],
      records: [],
    },
    {
      id: "arrival-checkin",
      title: "完成入住檢查",
      description: "領取鑰匙、核對房況、拍攝損壞紀錄並確認網路與基本設備。",
      phase: "arrival-72h",
      status: "not-started",
      priority: "high",
      predecessorIds: ["housing", "flight"],
      notes: "",
      templateKind: "housing",
      checklist: [
        { id: "keys", label: "領取並核對鑰匙", done: false },
        { id: "damage-photos", label: "完成房況拍照", done: false },
      ],
      records: [],
    },
    {
      id: "address-registration",
      title: "辦理住址登記",
      description: "依居住城市規定，在期限內備妥護照與房東入住證明辦理登記。",
      phase: "arrival-2w",
      status: "not-started",
      priority: "high",
      predecessorIds: ["arrival-checkin"],
      notes: "德國多數城市要求儘快登記，請以所在地官方規定為準。",
      checklist: [
        { id: "landlord-confirmation", label: "取得房東入住證明", done: false },
        { id: "registration-booking", label: "確認線上或臨櫃流程", done: false },
      ],
      records: [],
    },
    {
      id: "arrival-services",
      title: "完成銀行、SIM 與必要生活服務",
      description: "依個人情況處理銀行、限制帳戶撥款、SIM、交通票與廣電費。",
      phase: "arrival-2w",
      status: "not-started",
      priority: "medium",
      predecessorIds: ["address-registration"],
      notes: "服務商與價格會變動，不在模板中永久寫死。",
      checklist: [
        { id: "bank", label: "確認日常付款方式", done: false },
        { id: "sim", label: "完成手機網路", done: false },
        { id: "radio-fee", label: "確認住處廣電費分攤", done: false },
      ],
      records: [],
    },
    {
      id: "semester-admin",
      title: "追蹤選課、考試與學期行政",
      description: "將課表、考試登記、Learning Agreement 變更與成績單期限加入個人行事曆。",
      phase: "semester",
      status: "not-started",
      priority: "high",
      predecessorIds: ["learning-agreement"],
      notes: "旅行衝突檢查會使用你在旅行分頁加入的課程與考試。",
      templateKind: "course",
      checklist: [
        { id: "course-enrollment", label: "確認選課結果", done: false },
        { id: "exam-registration", label: "記錄考試登記期限", done: false },
      ],
      records: [],
    },
    {
      id: "return-checklist",
      title: "完成返國與註銷",
      description: "處理退租、押金、住址註銷、保險、交通票、SIM、銀行與成績單。",
      phase: "return",
      status: "not-started",
      priority: "high",
      predecessorIds: ["semester-admin"],
      notes: "各服務需要的提前通知天數不同，請個別查核。",
      checklist: [
        { id: "move-out", label: "完成退租與房間檢查", done: false },
        { id: "deregister", label: "完成住址註銷", done: false },
        { id: "transcript", label: "確認成績單與學分轉換", done: false },
      ],
      records: [],
    },
  ],
  bags: [
    { id: "checked", name: "托運行李", kind: "checked", limitKg: 23 },
    { id: "carry", name: "手提行李", kind: "carry-on", limitKg: 8 },
    { id: "personal", name: "個人物品", kind: "personal", limitKg: 3 },
  ],
  packingItems: [
    { id: "passport", name: "護照與隨身文件包", category: "文件", decision: "must", bagId: "personal", quantity: 1, weightKg: 0.45, packed: false },
    { id: "medication", name: "常用藥與英文處方", category: "健康", decision: "must", bagId: "carry", quantity: 1, weightKg: 0.5, packed: false, warning: "特殊藥品與數量需先查核入境規定。" },
    { id: "adapter", name: "歐規轉接頭", category: "電子", decision: "must", bagId: "carry", quantity: 2, weightKg: 0.12, packed: false },
    { id: "laptop", name: "筆電與充電器", category: "電子", decision: "must", bagId: "carry", quantity: 1, weightKg: 1.8, packed: false, warning: "鋰電池裝置通常需隨身攜帶。" },
    { id: "power-bank", name: "行動電源", category: "電子", decision: "recommend", bagId: "carry", quantity: 1, weightKg: 0.28, packed: false, warning: "不可托運；容量依航空公司規定。" },
    { id: "glasses", name: "備用眼鏡", category: "健康", decision: "recommend", bagId: "personal", quantity: 1, weightKg: 0.15, packed: false },
    { id: "coat", name: "適合季節的外套", category: "衣物", decision: "recommend", bagId: "checked", quantity: 1, weightKg: 1.2, packed: false },
    { id: "shoes", name: "好走的鞋", category: "衣物", decision: "recommend", bagId: "checked", quantity: 1, weightKg: 0.9, packed: false },
    { id: "bedding", name: "寢具", category: "生活", decision: "buy-there", bagId: "", quantity: 1, weightKg: 0, packed: false },
    { id: "liquids", name: "大瓶盥洗用品", category: "生活", decision: "buy-there", bagId: "", quantity: 1, weightKg: 0, packed: false },
    { id: "appliances", name: "高功率台灣電器", category: "電子", decision: "skip", bagId: "", quantity: 1, weightKg: 0, packed: false, warning: "先確認 230V 相容性。" },
  ],
  resources: [
    { id: "make-it-germany-study", title: "Make it in Germany：留學簽證", description: "德國政府提供的學生簽證與居留流程入口。", category: "簽證", type: "official", url: "https://www.make-it-in-germany.com/en/visa-residence/types/studying", verifiedAt: "2026-08-10", region: "Germany" },
    { id: "foreign-office-visa", title: "German Federal Foreign Office Visa Navigator", description: "依國籍與目的查找適用簽證與申請入口。", category: "簽證", type: "official", url: "https://digital.diplo.de/visa", verifiedAt: "2026-08-10", region: "Germany" },
    { id: "daad-insurance", title: "DAAD 健康保險指南", description: "國際學生入學與在德期間的健康保險要求概覽。", category: "醫療", type: "official", url: "https://www.daad.de/en/studying-in-germany/living-in-germany/health-insurance/", verifiedAt: "2026-08-10", region: "Germany" },
    { id: "customs-medicine", title: "德國海關：藥品", description: "個人用藥與特殊藥品的入境規定。", category: "海關", type: "official", url: "https://www.zoll.de/EN/Private-individuals/Travel/Entering-Germany/Restrictions/Medicinal-products-and-narcotics/medicinal-products-and-narcotics_node.html", verifiedAt: "2026-08-10", region: "Germany" },
    { id: "customs-food", title: "德國海關：食品", description: "肉類、乳製品與其他食品的入境限制。", category: "海關", type: "official", url: "https://www.zoll.de/EN/Private-individuals/Travel/Entering-Germany/Restrictions/Food-and-feed/food-and-feed_node.html", verifiedAt: "2026-08-10", region: "Germany" },
    { id: "radio-fee", title: "Rundfunkbeitrag 學生說明", description: "合租時的德國廣電費處理方式與官方回覆入口。", category: "生活", type: "official", url: "https://www.rundfunkbeitrag.de/welcome/english/students-and-apprentices", verifiedAt: "2026-08-10", region: "Germany" },
    { id: "packing-video-one", title: "德國留學行李經驗影片", description: "文件、藥品、電子用品與衣物的生活經驗整理。", category: "行李", type: "experience", url: "https://youtu.be/3QKMni6Vk28", verifiedAt: "2026-08-10", region: "Experience" },
    { id: "packing-video-two", title: "歐洲交換行李整理影片", description: "行李規劃與歐洲生活用品的經驗分享。", category: "行李", type: "experience", url: "https://youtu.be/6aabTZsFQRE", verifiedAt: "2026-08-10", region: "Experience" },
  ],
  budget: [
    { id: "rent", name: "每月住宿預算", amount: 500, cadence: "monthly", paid: false },
    { id: "food", name: "每月餐食與日用品", amount: 350, cadence: "monthly", paid: false },
    { id: "transport", name: "每月交通預算", amount: 60, cadence: "monthly", paid: false },
    { id: "arrival", name: "落地一次性支出", amount: 350, cadence: "once", paid: false },
  ],
  emergencyContact: "",
  travelPlans: [],
  studyEvents: [],
  aiInbox: { sources: [], proposals: [] },
};
