import type { AppState, JourneyPhase } from "./types";

export const phaseMeta: Record<JourneyPhase, { label: string; number: string; color: string }> = {
  admission: { label: "錄取與學校申請", number: "01", color: "blue" },
  visa: { label: "簽證與財力準備", number: "02", color: "yellow" },
  "pre-departure": { label: "住宿與行前手續", number: "03", color: "terracotta" },
  "arrival-72h": { label: "抵達 72 小時", number: "04", color: "sage" },
  "arrival-2w": { label: "抵達後兩週", number: "05", color: "blue" },
  semester: { label: "學期中生活與學業", number: "06", color: "yellow" },
  return: { label: "返國與註銷", number: "07", color: "terracotta" },
};

export const defaultState: AppState = {
  version: 1,
  dataRevision: 2,
  journey: {
    id: "austin-hdm-2627",
    kind: "exchange",
    title: "Austin 的德國交換年",
    ownerName: "Austin",
    homeCity: "Taipei",
    hostCity: "Stuttgart",
    hostSchool: "Hochschule der Medien",
    program: "Integrated Product Design",
    startDate: "2026-10-01",
    endDate: "2027-08-31",
    orientationDate: "2026-10-02",
    destinations: ["Stuttgart, Germany"],
  },
  tasks: [
    {
      id: "accept-place",
      title: "接受 HdM 交換名額",
      description: "確認 Integrated Product Design 的交換名額與兩學期交換期間。",
      phase: "admission",
      status: "done",
      priority: "high",
      dueDate: "2026-07-31",
      predecessorIds: [],
      notes: "已於 7/23 完成。",
      sourceLabel: "HdM",
      sourceUrl: "https://hdm-stuttgart.de/en/before-your-studies/preparation-for-your-studies/start-of-studies-for-exchange-students/",
      verifiedAt: "2026-08-08",
    },
    {
      id: "learning-agreement",
      title: "完成 Learning Agreement",
      description: "填妥 HdM Course List Form，確認第一學期課程後直接寄給 Minor Coordinator Prof. Manuel Hodrius。",
      phase: "admission",
      status: "in-progress",
      priority: "high",
      dueDate: "2026-09-04",
      predecessorIds: ["accept-place"],
      notes: "Course List 與簽名期限為 9/4；第二學期課程仍待 HdM 後續確認。",
      templateKind: "course",
      contactName: "Prof. Manuel Hodrius",
      checklist: [
        { id: "la-form-received", label: "收到 HdM Course List Form", done: true },
        { id: "la-course-list", label: "填妥第一學期預選課程", done: false },
        { id: "la-signature", label: "取得 Minor Coordinator 簽名", done: false },
        { id: "la-second-semester", label: "補上第二學期課程", done: false },
      ],
      records: [
        { id: "la-record-1", date: "2026-07-13", note: "HdM 說明 Learning Agreement 由錄取信列出的 Minor Coordinator 簽署。" },
        { id: "la-record-2", date: "2026-08-06", note: "收到 Course List Form，需在 9/4 前直接寄給 Prof. Manuel Hodrius。" },
      ],
      sourceLabel: "HdM / NCCU",
      verifiedAt: "2026-08-08",
    },
    {
      id: "semester-fee",
      title: "繳交 HdM 學期註冊費",
      description: "使用 HdM 提供的官方付款連結完成 €96.50 註冊費。",
      phase: "admission",
      status: "not-started",
      priority: "high",
      dueDate: "2026-08-15",
      predecessorIds: ["accept-place"],
      notes: "付款後保留收據，但不要把付款連結或收據上傳到這個網站。",
      templateKind: "payment",
      cost: 96.5,
      currency: "EUR",
      checklist: [
        { id: "fee-link", label: "確認官方付款連結", done: true },
        { id: "fee-pay", label: "完成付款", done: false },
        { id: "fee-receipt", label: "在私人資料夾保存收據", done: false },
      ],
      records: [
        { id: "fee-record-1", date: "2026-07-30", note: "已收到 HdM 線上付款資訊。" },
      ],
      sourceLabel: "HdM payment notice",
      verifiedAt: "2026-08-08",
    },
    {
      id: "blocked-account",
      title: "限制帳戶財力證明",
      description: "確認 Expatrio 入帳並保存 funded blocked-account confirmation。",
      phase: "visa",
      status: "done",
      priority: "high",
      predecessorIds: [],
      notes: "資金與官方證明已完成。",
      sourceLabel: "Expatrio",
      verifiedAt: "2026-08-08",
    },
    {
      id: "visa-online-resubmission",
      title: "完成簽證線上申請與補件重送",
      description: "依 Auslandsportal 通知修正護照文件與動機信，並重新送出學生簽證申請。",
      phase: "visa",
      status: "done",
      priority: "high",
      dueDate: "2026-08-04",
      predecessorIds: ["blocked-account"],
      notes: "修正版已於 8/4 重送，目前等待進一步審查或通知。",
      templateKind: "visa",
      checklist: [
        { id: "visa-online-passport", label: "重新上傳可接受的護照文件", done: true },
        { id: "visa-online-letter", label: "修正與申請資訊一致的動機信", done: true },
        { id: "visa-online-submit", label: "重新送出 Auslandsportal 申請", done: true },
      ],
      records: [
        { id: "visa-online-record-1", date: "2026-07-22", note: "首次透過 Auslandsportal 正式送出學生簽證申請。" },
        { id: "visa-online-record-2", date: "2026-08-04", note: "收到補件通知，當日修正護照文件與動機信後重新送出。" },
      ],
      result: "線上補件已完成；下一步是等待審查結果並準備 9/9 面談。",
      sourceLabel: "Auslandsportal",
      sourceUrl: "https://digital.diplo.de/nutzerkonto",
      verifiedAt: "2026-08-09",
    },
    {
      id: "visa-appointment",
      title: "德國學生簽證面談",
      description: "9/9 10:30 前往台北 101 德國在台協會；提早抵達並攜帶護照、預約確認與完整紙本文件。",
      phase: "visa",
      status: "not-started",
      priority: "high",
      dueDate: "2026-09-09",
      predecessorIds: ["visa-online-resubmission"],
      notes: "建議至少提早 30 分鐘到台北 101。",
      templateKind: "visa",
      scheduledAt: "2026-09-09T10:30",
      timeZone: "Asia/Taipei",
      location: "台北 101 33F｜德國在台協會",
      referenceNumber: "taip_25183959",
      cost: 75,
      currency: "EUR",
      checklist: [
        { id: "visa-passport", label: "護照正本", done: false },
        { id: "visa-confirmation", label: "紙本預約確認信", done: false },
        { id: "visa-documents", label: "完整簽證紙本文件", done: false },
        { id: "visa-cash", label: "準備等值新台幣現金簽證費", done: false },
      ],
      records: [
        { id: "visa-record-1", date: "2026-07-22", note: "已透過 Auslandsportal 正式送出學生簽證申請。" },
        { id: "visa-record-2", date: "2026-08-04", note: "護照文件與動機信完成修正並重新送出，目前等待審查。" },
      ],
      sourceLabel: "German Institute Taipei",
      sourceUrl: "https://taipei.diplo.de/tw-zh-tw/service/visa-einreise/2453292-2453292",
      verifiedAt: "2026-08-08",
    },
    {
      id: "flight",
      title: "確認航班與行李額度",
      description: "去程航班已購買：9/26 台北出發，10/1 經曼谷、伊斯坦堡抵達 Stuttgart。",
      phase: "pre-departure",
      status: "done",
      priority: "high",
      dueDate: "2026-07-27",
      predecessorIds: [],
      notes: "EVA：托運 2×23kg、手提 7kg；Turkish：托運合計 40kg、手提 8kg。全程配置需同時符合兩段限制。",
      templateKind: "flight",
      scheduledAt: "2026-09-26T07:50",
      timeZone: "Asia/Taipei",
      location: "TPE → BKK → IST → STR",
      checklist: [
        { id: "flight-ticket", label: "完成去程航班購買", done: true },
        { id: "flight-baggage", label: "確認兩段航空公司的實際行李額度", done: true },
        { id: "flight-arrival", label: "確認 10/1 17:50 抵達 Stuttgart", done: true },
      ],
      records: [
        { id: "flight-record-1", date: "2026-07-27", note: "航班已購買；9/26 自台北出發，10/1 17:50 抵達 Stuttgart Airport。" },
      ],
      result: "去程交通已確認；剩下的是把抵達方式告知 Buddy，並安排從機場前往宿舍與領鑰匙。",
    },
    {
      id: "buddy",
      title: "和 HdM Buddy 聯絡",
      description: "Buddy Florian 已主動聯絡；下一步告知改為 10/1 17:50 直抵 Stuttgart，詢問帶行李前往宿舍的最佳方式。",
      phase: "pre-departure",
      status: "in-progress",
      priority: "medium",
      dueDate: "2026-08-31",
      predecessorIds: [],
      notes: "原先討論 Munich 到 Stuttgart 的 FlixBus；行程已改為飛抵 Stuttgart Airport，需要更新 Buddy。",
      templateKind: "school-admin",
      contactName: "Florian Lampl｜HdM Buddy",
      checklist: [
        { id: "buddy-contact", label: "收到 Buddy 聯絡方式", done: true },
        { id: "buddy-arrival", label: "告知抵達日期與交通方式", done: false },
        { id: "buddy-route", label: "詢問 Stuttgart Airport 到宿舍的行李友善路線", done: false },
      ],
      records: [
        { id: "buddy-record-1", date: "2026-07-25", note: "Florian 主動聯絡並提供抵達、交通、註冊與住宿協助。" },
        { id: "buddy-record-2", date: "2026-08-09", note: "抵達計畫改為 10/1 17:50 直飛 Stuttgart；待傳訊更新 Buddy。" },
      ],
      sourceLabel: "HdM Buddy Programme",
      sourceUrl: "https://hdm-stuttgart.de/en/before-your-studies/preparation-for-your-studies/start-of-studies-for-exchange-students/",
      verifiedAt: "2026-08-08",
    },
    {
      id: "key-pickup",
      title: "預約宿舍鑰匙交接",
      description: "聯絡 Hausmeister 確認 Filderbahnplatz 住宿的鑰匙領取時間與辦公室位置。",
      phase: "pre-departure",
      status: "not-started",
      priority: "high",
      dueDate: "2026-09-25",
      predecessorIds: ["flight"],
      notes: "住宿詳細地址與房號保留在私人文件，不放入本站。",
      templateKind: "housing",
      location: "Hausmeisterbüro｜Filderbahnplatz 37 ground floor",
      contactName: "Hausmeister Herr Jäger",
      checklist: [
        { id: "key-contact", label: "聯絡 Hausmeister", done: false },
        { id: "key-time", label: "確認領鑰匙日期與時間", done: false },
        { id: "key-letter", label: "把入住確認信放入隨身文件包", done: false },
      ],
      records: [
        { id: "key-record-1", date: "2026-07-07", note: "已收到宿舍入住確認信與鑰匙領取資訊。" },
      ],
      sourceLabel: "Studierendenwerk move-in letter",
      verifiedAt: "2026-08-08",
    },
    {
      id: "arrival-food",
      title: "準備第一晚食物與網路",
      description: "確認抵達日超市營業時間，備妥少量歐元、離線地圖、eSIM 或可用漫遊。",
      phase: "arrival-72h",
      status: "not-started",
      priority: "medium",
      dueDate: "2026-10-01",
      predecessorIds: ["flight"],
      notes: "德國多數超市週日休息，若行程延誤要有備案。",
    },
    {
      id: "move-in",
      title: "宿舍入住與房況紀錄",
      description: "領鑰匙、檢查家具設備、拍攝既有損壞、確認信箱姓名與取得房東證明。",
      phase: "arrival-72h",
      status: "not-started",
      priority: "high",
      dueDate: "2026-10-01",
      predecessorIds: ["key-pickup"],
      notes: "照片只保存在自己的裝置，不上傳到本站。",
    },
    {
      id: "orientation",
      title: "參加 HdM 必到 Orientation",
      description: "10/2 10:00 參加入學說明，確認報到、課程系統、學生信箱與學生證流程。",
      phase: "arrival-72h",
      status: "not-started",
      priority: "high",
      dueDate: "2026-10-02",
      predecessorIds: ["move-in"],
      notes: "設鬧鐘並預留從宿舍到校的交通時間。",
      templateKind: "school-admin",
      scheduledAt: "2026-10-02T10:00",
      timeZone: "Europe/Berlin",
      location: "HdM Stuttgart｜地點待學校確認",
      checklist: [
        { id: "orientation-route", label: "前一天確認交通路線與教室", done: false },
        { id: "orientation-alarm", label: "設定鬧鐘與出門時間", done: false },
      ],
      records: [],
      sourceLabel: "HdM acceptance information",
      verifiedAt: "2026-08-08",
    },
    {
      id: "anmeldung",
      title: "完成 Stuttgart 住址登記",
      description: "帶護照與房東證明，在搬入兩週內完成 Anmeldung；完成後保存登記證明。",
      phase: "arrival-2w",
      status: "not-started",
      priority: "high",
      dueDate: "2026-10-14",
      predecessorIds: ["move-in"],
      notes: "可查看線上登記資格；若不適用則預約 Bürgerbüro。",
      templateKind: "school-admin",
      location: "Stuttgart Bürgerbüro｜預約後填寫",
      checklist: [
        { id: "anmeldung-passport", label: "護照", done: false },
        { id: "anmeldung-landlord", label: "房東入住證明 Wohnungsgeberbestätigung", done: false },
        { id: "anmeldung-save", label: "保存 Meldebescheinigung", done: false },
      ],
      records: [],
      sourceLabel: "City of Stuttgart",
      sourceUrl: "https://www.stuttgart.de/en/organigramm/leistungen/wohnsitz-anmelden-als-hauptwohnsitz",
      verifiedAt: "2026-08-08",
    },
    {
      id: "bank-sepa",
      title: "開通德國／SEPA 銀行功能",
      description: "完成銀行帳戶與稅務資料，啟用限制帳戶月撥款並設定宿舍租金扣款。",
      phase: "arrival-2w",
      status: "not-started",
      priority: "high",
      dueDate: "2026-10-16",
      predecessorIds: ["anmeldung"],
      notes: "核對 SWS 最新 SEPA 指示。",
    },
    {
      id: "health-insurance",
      title: "啟用 TK 學生保險",
      description: "確認入學所需電子保險狀態、保險生效日與就醫卡寄送地址。",
      phase: "arrival-2w",
      status: "not-started",
      priority: "high",
      dueDate: "2026-10-16",
      predecessorIds: ["anmeldung"],
      notes: "入境保險與學生公保的生效區間不要留空窗。",
      sourceLabel: "DAAD health insurance guide",
      sourceUrl: "https://www.daad.de/en/studying-in-germany/living-in-germany/health-insurance/",
      verifiedAt: "2026-08-08",
    },
    {
      id: "student-id-ticket",
      title: "啟用學生證與交通票",
      description: "啟用 HdM 學生證，依當學期規則申請 VVS 學生 Deutschland-Ticket。",
      phase: "arrival-2w",
      status: "not-started",
      priority: "medium",
      dueDate: "2026-10-16",
      predecessorIds: ["orientation"],
      notes: "價格可能變動，購買前重新查核官方頁面。",
      sourceLabel: "VVS",
      sourceUrl: "https://www.vvs.de/en/tickets-and-subscriptions/deutschland-ticket-for-students",
      verifiedAt: "2026-08-08",
    },
    {
      id: "radio-fee",
      title: "處理 Rundfunkbeitrag 廣電費",
      description: "收到信後與室友確認同一 dwelling 的繳費人與 contribution number，再正確回覆。",
      phase: "semester",
      status: "not-started",
      priority: "medium",
      predecessorIds: ["anmeldung"],
      notes: "合租通常每戶一人繳，不要每個室友重複付款。",
      sourceLabel: "Rundfunkbeitrag",
      sourceUrl: "https://www.rundfunkbeitrag.de/welcome/english/students-and-apprentices",
      verifiedAt: "2026-08-08",
    },
    {
      id: "exam-registration",
      title: "確認考試登記期限",
      description: "查看 HdM Academic Calendar 與課程系統，將每門課的考試或作業登記期限加入行事曆。",
      phase: "semester",
      status: "not-started",
      priority: "high",
      predecessorIds: ["orientation"],
      notes: "本站不預設尚未確認的日期。",
      templateKind: "course",
      checklist: [
        { id: "exam-course-list", label: "逐門課確認是否需要登記", done: false },
        { id: "exam-calendar", label: "將每門課期限加入行事曆", done: false },
      ],
      records: [],
      sourceLabel: "HdM Academic Calendar",
      sourceUrl: "https://hdm-stuttgart.de/en/before-your-studies/preparation-for-your-studies/start-of-studies-for-exchange-students/academic-calendar/",
      verifiedAt: "2026-08-08",
    },
    {
      id: "mental-health",
      title: "收藏心理與社會諮詢入口",
      description: "先保存免費、保密的心理、社會與法律諮詢資源，需要時不用臨時搜尋。",
      phase: "semester",
      status: "not-started",
      priority: "low",
      predecessorIds: [],
      notes: "這是安全網，不代表一定要預約。",
      sourceLabel: "Studierendenwerk Stuttgart",
      sourceUrl: "https://www.studierendenwerk-stuttgart.de/en/counselling",
      verifiedAt: "2026-08-08",
    },
    {
      id: "housing-cancel",
      title: "確認退宿與房間檢查",
      description: "確認退租日期、清潔標準、鑰匙歸還、押金退回帳戶與最終房間檢查。",
      phase: "return",
      status: "not-started",
      priority: "high",
      dueDate: "2027-07-31",
      predecessorIds: [],
      notes: "依正式租約與 SWS 最新退宿通知辦理。",
    },
    {
      id: "deregister",
      title: "辦理住址註銷",
      description: "搬離德國前後依 Stuttgart 規則完成 Abmeldung，保存註銷證明供其他合約使用。",
      phase: "return",
      status: "not-started",
      priority: "high",
      dueDate: "2027-08-31",
      predecessorIds: ["housing-cancel"],
      notes: "搬往國外可使用 Stuttgart 線上服務。",
      sourceLabel: "City of Stuttgart",
      sourceUrl: "https://www.stuttgart.de/en/organigramm/leistungen/wohnsitz-abmelden",
      verifiedAt: "2026-08-08",
    },
    {
      id: "transcript-return",
      title: "取得成績單與完成學分轉換",
      description: "確認 HdM 成績單寄送方式，保存課程描述並向 NCCU 完成返國學分認定。",
      phase: "return",
      status: "not-started",
      priority: "medium",
      dueDate: "2027-09-15",
      predecessorIds: ["exam-registration"],
      notes: "返國前先確認承辦窗口與需要的正本。",
    },
  ],
  bags: [
    { id: "checked-1", name: "托運行李 A", kind: "checked", limitKg: 23 },
    { id: "checked-2", name: "托運行李 B", kind: "checked", limitKg: 23 },
    { id: "carry-on", name: "手提行李", kind: "carry-on", limitKg: 7 },
    { id: "personal", name: "隨身小包", kind: "personal", limitKg: 3 },
  ],
  packingItems: [
    { id: "passport", name: "護照與簽證文件包", category: "文件", decision: "must", bagId: "personal", quantity: 1, weightKg: 0.45, packed: false },
    { id: "copies", name: "重要文件紙本副本", category: "文件", decision: "must", bagId: "carry-on", quantity: 1, weightKg: 0.6, packed: false },
    { id: "laptop", name: "筆電與充電器", category: "電子", decision: "must", bagId: "carry-on", quantity: 1, weightKg: 2.1, packed: false, warning: "鋰電池設備建議隨身攜帶並依航空公司規則處理。" },
    { id: "adapter", name: "歐規轉接頭", category: "電子", decision: "must", bagId: "carry-on", quantity: 2, weightKg: 0.12, packed: false },
    { id: "powerbank", name: "行動電源", category: "電子", decision: "must", bagId: "personal", quantity: 1, weightKg: 0.35, packed: false, warning: "不可托運；容量與標示須符合航空公司規定。" },
    { id: "medicine", name: "個人處方與常備藥", category: "醫療", decision: "must", bagId: "carry-on", quantity: 1, weightKg: 0.65, packed: false, warning: "保留處方或醫師證明；管制藥品另查德國海關要求。" },
    { id: "glasses", name: "備用眼鏡／隱形眼鏡", category: "醫療", decision: "recommend", bagId: "personal", quantity: 1, weightKg: 0.2, packed: false },
    { id: "coat", name: "防風防水外套", category: "衣物", decision: "must", bagId: "checked-1", quantity: 1, weightKg: 1.1, packed: false },
    { id: "layers", name: "可分層穿搭上衣", category: "衣物", decision: "recommend", bagId: "checked-1", quantity: 7, weightKg: 0.28, packed: false },
    { id: "shoes", name: "好走防潑水鞋", category: "衣物", decision: "must", bagId: "checked-2", quantity: 1, weightKg: 1.2, packed: false },
    { id: "formal", name: "一套稍正式服裝", category: "衣物", decision: "recommend", bagId: "checked-2", quantity: 1, weightKg: 0.9, packed: false },
    { id: "towel", name: "第一晚快乾毛巾", category: "生活", decision: "recommend", bagId: "checked-2", quantity: 1, weightKg: 0.32, packed: false },
    { id: "bedding", name: "寢具與厚棉被", category: "生活", decision: "buy-there", bagId: "", quantity: 1, weightKg: 0, packed: false },
    { id: "cookware", name: "鍋具與大量餐具", category: "生活", decision: "buy-there", bagId: "", quantity: 1, weightKg: 0, packed: false },
    { id: "food", name: "少量家鄉調味料", category: "食品", decision: "recommend", bagId: "checked-2", quantity: 1, weightKg: 0.5, packed: false, warning: "含肉、乳製品或其他受限制食品應先查德國海關。" },
    { id: "dryer", name: "高瓦數吹風機", category: "電子", decision: "skip", bagId: "", quantity: 1, weightKg: 0, packed: false },
    { id: "memory", name: "一件有紀念意義的小物", category: "心情", decision: "recommend", bagId: "checked-1", quantity: 1, weightKg: 0.25, packed: false },
  ],
  resources: [
    { id: "hdm-start", title: "HdM 交換生 Start Guide", description: "Buddy、行政流程、選課、學生證與交通票的官方入口。", category: "學校", type: "school", url: "https://hdm-stuttgart.de/en/before-your-studies/preparation-for-your-studies/start-of-studies-for-exchange-students/", verifiedAt: "2026-08-08", region: "HdM / Stuttgart" },
    { id: "hdm-calendar", title: "HdM Academic Calendar", description: "學期日期、假期與考試登記等時程。", category: "學業", type: "school", url: "https://hdm-stuttgart.de/en/before-your-studies/preparation-for-your-studies/start-of-studies-for-exchange-students/academic-calendar/", verifiedAt: "2026-08-08", region: "HdM" },
    { id: "anmeldung-resource", title: "Stuttgart 住址登記", description: "搬入後兩週內辦理 Anmeldung，並準備房東證明。", category: "行政", type: "city", url: "https://www.stuttgart.de/en/organigramm/leistungen/wohnsitz-anmelden-als-hauptwohnsitz", verifiedAt: "2026-08-08", region: "Stuttgart" },
    { id: "residence-resource", title: "學生居留許可", description: "Stuttgart 外管局的學生居留申請與所需資料。", category: "行政", type: "city", url: "https://www.stuttgart.de/en/organigramm/leistungen/aufenthaltserlaubnis-beantragen-zum-zweck-des-studiums-sprachkurs-schulbesuch", verifiedAt: "2026-08-08", region: "Stuttgart" },
    { id: "insurance-resource", title: "DAAD 健康保險指南", description: "國際學生入學與在德期間的健康保險要求概覽。", category: "醫療", type: "official", url: "https://www.daad.de/en/studying-in-germany/living-in-germany/health-insurance/", verifiedAt: "2026-08-08", region: "Germany" },
    { id: "vvs-resource", title: "VVS 學生 Deutschland-Ticket", description: "適用條件、範圍與最新價格；購買前重新查核。", category: "交通", type: "official", url: "https://www.vvs.de/en/tickets-and-subscriptions/deutschland-ticket-for-students", verifiedAt: "2026-08-08", region: "Stuttgart / Germany" },
    { id: "radio-resource", title: "Rundfunkbeitrag 學生說明", description: "合租的廣電費處理方式與官方回覆入口。", category: "生活", type: "official", url: "https://www.rundfunkbeitrag.de/welcome/english/students-and-apprentices", verifiedAt: "2026-08-08", region: "Germany" },
    { id: "counselling-resource", title: "Studierendenwerk 諮詢服務", description: "免費、保密的心理、社會與法律諮詢。", category: "支援", type: "official", url: "https://www.studierendenwerk-stuttgart.de/en/counselling", verifiedAt: "2026-08-08", region: "Stuttgart" },
    { id: "customs-medicine", title: "德國海關：藥品與管制藥品", description: "個人用藥與特殊藥品入境規則。", category: "海關", type: "official", url: "https://www.zoll.de/EN/Private-individuals/Travel/Entering-Germany/Restrictions/Medicinal-products-and-narcotics/medicinal-products-and-narcotics_node.html", verifiedAt: "2026-08-08", region: "Germany" },
    { id: "customs-food", title: "德國海關：食品與飼料", description: "肉類、乳製品與其他食品入境限制。", category: "海關", type: "official", url: "https://www.zoll.de/EN/Private-individuals/Travel/Entering-Germany/Restrictions/Food-and-feed/food-and-feed_node.html", verifiedAt: "2026-08-08", region: "Germany" },
    { id: "video-one", title: "德國留學行李經驗影片", description: "文件、藥品、電子用品、衣物與不建議攜帶品的經驗分類。", category: "行李", type: "experience", url: "https://youtu.be/3QKMni6Vk28", verifiedAt: "2026-08-08", region: "Experience" },
    { id: "video-two", title: "歐洲交換行李整理影片", description: "行李規劃與歐洲生活用品的經驗分享。", category: "行李", type: "experience", url: "https://youtu.be/6aabTZsFQRE", verifiedAt: "2026-08-08", region: "Experience" },
    { id: "deregister-resource", title: "Stuttgart 住址註銷", description: "搬往國外時使用的 Abmeldung 線上與臨櫃資訊。", category: "返國", type: "city", url: "https://www.stuttgart.de/en/organigramm/leistungen/wohnsitz-abmelden", verifiedAt: "2026-08-08", region: "Stuttgart" },
  ],
  budget: [
    { id: "rent", name: "學生宿舍租金", amount: 393, cadence: "monthly", paid: false },
    { id: "semester-fee-budget", name: "HdM 學期註冊費", amount: 96.5, cadence: "once", paid: false },
    { id: "transport", name: "學生交通票預留", amount: 35, cadence: "monthly", paid: false },
    { id: "groceries", name: "餐食與日用品預算", amount: 320, cadence: "monthly", paid: false },
    { id: "arrival-shopping", name: "落地寢具／生活用品", amount: 220, cadence: "once", paid: false },
  ],
  emergencyContact: "",
  travelPlans: [],
  studyEvents: [
    {
      id: "hdm-orientation-study-event",
      title: "HdM Mandatory Orientation",
      kind: "orientation",
      startDate: "2026-10-02",
      startTime: "10:00",
      mandatory: true,
      notes: "交換生必到；規劃旅行時不可排在這一天。",
    },
    {
      id: "course-list-deadline-study-event",
      title: "Course List / Learning Agreement 截止",
      kind: "deadline",
      startDate: "2026-09-04",
      mandatory: true,
      notes: "若旅行涵蓋前後日期，需確認文件已提前寄出。",
    },
    {
      id: "visa-appointment-study-event",
      title: "德國學生簽證面談",
      kind: "deadline",
      startDate: "2026-09-09",
      startTime: "10:30",
      mandatory: true,
      notes: "台北 101，行程不得衝突。",
    },
  ],
};
